# Linear Algebra Quiz1

> 해당 퀴즈에서는 강의에서 직접적으로 다루지 않은 문제들도 포함되어 있습니다. 성취도 확인용으로 진행되는 시험이니 한 주 동안 배운 내용을 복습하고 새로운 문제들을 공부하는 데 의미를 두시면 좋을 것 같습니다. 계산이 필요할 경우 손으로 계산하셔도 되고, 각자 colab을 켜서 numpy 등의 package를 사용하셔도 됩니다.

In [11]:
import numpy as np
import sympy as sy
from sympy.solvers.solveset import linsolve

## 다음 명제에 대해, True/False를 판단하시오. True일 경우 간략하게 이유를 서술하고, False일 경우 간략하게 이유를 설명하거나 반례를 드시오.

\\

행렬 $A,B$에 대해

\\

1. $A$와 $B$가 invertible 하다면, $(AB)^{-1} = A^{-1}B^{-1}$이 성립한다. \\



In [7]:
A = np.array([[1, 2],
             [3, 4]])
B = np.array([[1, 2],
             [3, 5]])
np.linalg.inv(A@B) == np.linalg.inv(A) @ np.linalg.inv(B)

array([[False, False],
       [False, False]])

A: False

---



2. $\begin{bmatrix} 1 & 1 \\ 0 & 1 \\ 0 & 0 \end{bmatrix} \begin{bmatrix}x1\\x2\end{bmatrix} = \begin{bmatrix} 3 \\ 1 \\ 0\end{bmatrix}$는 해가 존재한다. \\

In [13]:
A = sy.Matrix(((1, 1),(0, 1),(0, 0)))
b = sy.Matrix((3, 1, 0))
system = A,b
x1, x2, x3 = sy.symbols('x1 x2 x3')
linsolve(system, x1, x2, x3)

FiniteSet((2, 1, x3))

A: True

---

해가 무수히 많다.

3. $\begin{bmatrix} 1 & 1 \\ 0 & 1 \\ 0 & 0 \end{bmatrix} \begin{bmatrix}x1\\x2\end{bmatrix} = \begin{bmatrix} 3 \\ 1 \\ 1\end{bmatrix}$은 해가 존재한다. \\


In [14]:
A = sy.Matrix(((1, 1),(0, 1),(0, 0)))
b = sy.Matrix((3, 1, 1))
system = A,b
x1, x2, x3 = sy.symbols('x1 x2 x3')
linsolve(system, x1, x2, x3)

EmptySet

A: False

---

해가 존재하지 않는다.

4. $\begin{bmatrix} 3 & 2 \\ 5 & 1 \\ 0 & 0 \end{bmatrix}$의 column space는 span($\{ \begin{bmatrix} 1 \\ 0 \\ 0\end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 0\end{bmatrix}\}$)과 같다. \\

A: True

---

똑같은 평면을 이룬다.

5. $R^2$는 $R^3$의 subspace이다.

A: True

---

R3의 공간은 R2의 평면을 포함한다.

6. Vector $x \in R^2$에 대한 Transformation $T_1$: (1) x축에 대해 reflection 후 (2) y축에 대해 reflection. \\
 Vector $x \in R^2$에 대한 Transformatiopn $T_2$: 시계방향으로 180도 회전. \\
 이때 $T_1$은 $T_2$와 같다. \\

In [15]:
t1 = np.array([[1, 0],
               [0, -1]])
t2 = np.array([[-1, 0],
               [0, 1]])
T1 = t2@t1
T2 = np.array([[-1, 0],
               [0, -1]])

T1 == T2

array([[ True,  True],
       [ True,  True]])

A: True

---



7. A,B가 각각 invertible하면, $(A+B)^{-1} = A^{-1} + B^{-1}$ 이다.

In [17]:
A = np.array([[1, 2],
             [3, 4]])
B = np.array([[1, 2],
             [3, 5]])
np.linalg.inv(A+B) == np.linalg.inv(A) + np.linalg.inv(B)

array([[False, False],
       [False, False]])

A: False

---



8. $T(x) = Ax = \begin{bmatrix} 3 & 2 \\ 5 & 1 \\ 0 & 0 \end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}$는 $R^2$에서 $R^3$으로 ONTO mapping하는 transformation이다.

A: False

---

span(A)가 $R^{2}$이다

9. $T(x) = Ax = \begin{bmatrix} 3 & 2 \\ 5 & 1 \\ 0 & 0 \end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix}$는 $R^2$에서 $R^3$으로 one-to-one mapping하는 transformation이다.

A: True

---

A가 linearly independent하다

10. $T(x) = Ax = \begin{bmatrix} 1 & 0 &0&5&0\\ 0 & 1 &0&1&0\\ 0 & 0&1&0&0\\0&0&0&0&1 \end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}$는 $R^5$에서 $R^4$으로 ONTO mapping하는 transformation이다.

A. True

---

column [5, 1, 0, 0]은 linearly dependent하여 span(A)가 $R^{4}$이다

11. $T(x) = Ax = \begin{bmatrix} 1 & 0 &0&5&0\\ 0 & 1 &0&1&0\\ 0 & 0&1&0&0\\0&0&0&0&1 \end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}$는 $R^5$에서 $R^4$으로 one-to-one mapping하는 transformation이다.

A. False

---

A가 linearly dependent하다

12. $T: R^n \rightarrow R^n$ 인 $T$가 one-to-one linear transformation이면, $T$는 ONTO linear transformation이다.

A. True

---

같은 차원으로 일대일 대응이므로 ONTO 선형변환이다

13. $T: R^n \rightarrow R^n$ 인 $T$가 ONTO linear transformation이면, $T$는 one-to-one linear transformation이다.

A. False

---

T가 linearly dependent하면 성립하지 않는다

14. $A$가 $n \times n$ matrix이면서 rank가 $n$인 경우, $A$는 invertible 하다.

A. True

---

A가 ONTO linear transformation이면서 one-to-one transformation이기 때문이다

15. $A = \begin{bmatrix} 1 & 1 & 1\\ 2 & 2& 2 \\ 3 & 3& 3 \end{bmatrix}$은 invertible하지 않다.

In [19]:
A = sy.Matrix([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])
A.det()

0

A. True

---

A의 판별식이 0이다

16. $A$와 $B$의 rank가 같다면, 두 matrix의 shape은 같다.

In [23]:
A = np.array([1, 0])
B = np.array([[1, 0],
              [1, 0]])
print(A)
print(B)

[1 0]
[[1 0]
 [1 0]]


A. False

---

위 A와 B는 rank가 1로 같지만 shape가 다르다

17. $AB = BC$이면, $B=C$이다.

A. False

---

A와 C가 항등행렬이면 왼쪽 식이 성립하고 이때 B는 항등행렬이 아니어도 된다

18. $B = A^TA$이면, $B$는 symmetric matrix이다.

A. True

---

행렬곱 수행시에 대칭적으로 같은 벡터끼리 곱해진다

19. Vector $v_1, v_2, v_3, v_4, v_5$가 $R^5$를 span한다면, 저 다섯 vector는 서로 linearly independent하다.

A. True

---

linearly denendent한 벡터가 있으면 span의 차원이 줄어든다

20. $v_1, v_2, v_3 \in R^3$인 세 vector가 서로 linearly dependent 하다면, 세 vector를 칼럼으로 하는 matrix $A = \begin{bmatrix} \mid & \mid & \mid \\ v_1 & v_2 & v_3 \\ \mid & \mid & \mid  \end{bmatrix}$는 invertible하지 않다.

A. True

---

변환행렬이 one-to-one transformation이 아니다

21. $v_1, v_2 \in R^3$인 두 vector가 span하는 subspace는 평면이다 (2 dimensional subspace).

A. False

---

v1, v2가 linearly dependent하면 1 dimensional subspace를 갖는다

22. Normal equation은 해가 항상 존재한다.

A. True

---

한개 혹은 무수히 많게 존재한다

23. $m \times n$ matrix $A$의 column vector $v_1,v_2, \cdots, v_n$이 orthonormal 하다면,  $AA^Tx$는 $x$를 Col $A$에 orthogonal projection하는 matrix이다.

In [41]:
A = np.array([[1, 1],
             [2, 2]])
x = np.array([2, 2])

B = A @ A.T @ x

C = B-A[:][0]

C.dot(A[0])

34

 A. False

---

A와 x를 위와 같이 했을 때 x에서 A에 orthogonal projection을 계산한 벡터 C를 A의 벡터 중 하나와 내적했을 때 0이 나오지 않는다

24. $m \times n$ matrix $A$의 column vector $v_1,v_2, \cdots, v_n$이 서로 linearly independent 하다고 하자. 그렇다면 $v_1,v_2, \cdots, v_n$에 Gram-Schmidt를 적용하면 Col $A$의 orthogonal basis가 된다.

A. True

---

A의 벡터들이 linearly independent하면 Gram-Schmidt을 적용했을 때 span이 서로 같다

25. Subspace $V$ = span ($\Bigg\{ \begin{bmatrix} 3 \\ 1 \\ 0\end{bmatrix}\, \begin{bmatrix} 1 \\ 2 \\ 0\end{bmatrix}\Bigg\}$)라고 하자. 이때 ($\Bigg\{ \begin{bmatrix} 1 \\ 1 \\ 0\end{bmatrix}\, \begin{bmatrix} 0 \\ 0 \\ 1\end{bmatrix}\Bigg\}$)은 $V$의 orthogonal basis가 된다.

A. False

---

두 span이 표현하는 평면이 다르다

26. 어떤 임의의 n개의 vector set이 주어졌을 때, Gram-Schmidt orthonormalization을 이용하면, 서로 orthonormal한 n개의 vector set으로 만들 수 있다.

A. False

---

임의의 n개의 vector set이 linearly dependent일 때 Gram-Schmidt orthonormalization을 이용하면 서로 orthonormal한 vector set이 n개보다 적게 만들어진다

27. $A^TA=0$이면, $A=0$이다.

A. True

---

$A^TA$은 행렬의 대각선이 A의 각 column의 제곱합인데 0이면 column의 모든 원소가 0이다

28.  $x_1=x_3$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.

A. True

---

span(H)는 $R^{2}$이다

29. $x_2=1$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. True

---

span(H)는 $R^{2}$이다

30. $x_1x_2=0$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. True

---

span(H)는 두 개의 평면이 나오고 $R^{3}$의 subspace가 된다

31. $x_1+x_2+x_3=0$를 만족하는 vector $x=\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}$의 set을 $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. True

---

span(H)의 차원은 3차원보다 커지지 못한다

32. span$\Bigg\{\begin{bmatrix}1 \\ 2 \\ 3 \end{bmatrix}, \begin{bmatrix}1 \\ 3 \\ 5 \end{bmatrix} \Bigg\}$를  $H$라고 하자. $H$는 $R^3$의 subspace이다.


A. True

---

span(H)는 $R^{2}$이다

33. 어떤 vector $x$를 subspace $H$로 orthogonal projection 하는 matrix는 여러 개가 나올 수 있다.

A. True

---

H가 3차원보다 크면 orthogonal projection 하는 matrix가 여러 개가 나올 수 있다

34. Least square 문제에서 error, $b - Ax$는 0이 나올 수 없다.

A. False

---

x가 항등행렬, A, b가 서로 같으면 0이 나올 수 있다

35. QR factorization은 square matrix에만 할 수 있다.  

In [26]:
A = np.array([[1, 2, 3], [2, 3, 4]])
Q,R = np.linalg.qr(A)
print(Q)
print(R)

[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
[[-2.23606798 -3.57770876 -4.91934955]
 [ 0.         -0.4472136  -0.89442719]]


A. False

---

